// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/dev-hyunsang/golang-crud-with-entgo/ent/predicate"
	"github.com/dev-hyunsang/golang-crud-with-entgo/ent/todo"
	"github.com/google/uuid"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeToDo = "ToDo"
)

// ToDoMutation represents an operation that mutates the ToDo nodes in the graph.
type ToDoMutation struct {
	config
	op            Op
	typ           string
	id            *int
	todo_uuid     *uuid.UUID
	todo          *string
	_done         *bool
	created_at    *time.Time
	edited_at     *time.Time
	deleted_at    *time.Time
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*ToDo, error)
	predicates    []predicate.ToDo
}

var _ ent.Mutation = (*ToDoMutation)(nil)

// todoOption allows management of the mutation configuration using functional options.
type todoOption func(*ToDoMutation)

// newToDoMutation creates new mutation for the ToDo entity.
func newToDoMutation(c config, op Op, opts ...todoOption) *ToDoMutation {
	m := &ToDoMutation{
		config:        c,
		op:            op,
		typ:           TypeToDo,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withToDoID sets the ID field of the mutation.
func withToDoID(id int) todoOption {
	return func(m *ToDoMutation) {
		var (
			err   error
			once  sync.Once
			value *ToDo
		)
		m.oldValue = func(ctx context.Context) (*ToDo, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ToDo.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withToDo sets the old ToDo of the mutation.
func withToDo(node *ToDo) todoOption {
	return func(m *ToDoMutation) {
		m.oldValue = func(context.Context) (*ToDo, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ToDoMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ToDoMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ToDoMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ToDoMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ToDo.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTodoUUID sets the "todo_uuid" field.
func (m *ToDoMutation) SetTodoUUID(u uuid.UUID) {
	m.todo_uuid = &u
}

// TodoUUID returns the value of the "todo_uuid" field in the mutation.
func (m *ToDoMutation) TodoUUID() (r uuid.UUID, exists bool) {
	v := m.todo_uuid
	if v == nil {
		return
	}
	return *v, true
}

// OldTodoUUID returns the old "todo_uuid" field's value of the ToDo entity.
// If the ToDo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ToDoMutation) OldTodoUUID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTodoUUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTodoUUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTodoUUID: %w", err)
	}
	return oldValue.TodoUUID, nil
}

// ResetTodoUUID resets all changes to the "todo_uuid" field.
func (m *ToDoMutation) ResetTodoUUID() {
	m.todo_uuid = nil
}

// SetTodo sets the "todo" field.
func (m *ToDoMutation) SetTodo(s string) {
	m.todo = &s
}

// Todo returns the value of the "todo" field in the mutation.
func (m *ToDoMutation) Todo() (r string, exists bool) {
	v := m.todo
	if v == nil {
		return
	}
	return *v, true
}

// OldTodo returns the old "todo" field's value of the ToDo entity.
// If the ToDo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ToDoMutation) OldTodo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTodo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTodo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTodo: %w", err)
	}
	return oldValue.Todo, nil
}

// ResetTodo resets all changes to the "todo" field.
func (m *ToDoMutation) ResetTodo() {
	m.todo = nil
}

// SetDone sets the "done" field.
func (m *ToDoMutation) SetDone(b bool) {
	m._done = &b
}

// Done returns the value of the "done" field in the mutation.
func (m *ToDoMutation) Done() (r bool, exists bool) {
	v := m._done
	if v == nil {
		return
	}
	return *v, true
}

// OldDone returns the old "done" field's value of the ToDo entity.
// If the ToDo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ToDoMutation) OldDone(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDone: %w", err)
	}
	return oldValue.Done, nil
}

// ResetDone resets all changes to the "done" field.
func (m *ToDoMutation) ResetDone() {
	m._done = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *ToDoMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ToDoMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the ToDo entity.
// If the ToDo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ToDoMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ToDoMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetEditedAt sets the "edited_at" field.
func (m *ToDoMutation) SetEditedAt(t time.Time) {
	m.edited_at = &t
}

// EditedAt returns the value of the "edited_at" field in the mutation.
func (m *ToDoMutation) EditedAt() (r time.Time, exists bool) {
	v := m.edited_at
	if v == nil {
		return
	}
	return *v, true
}

// OldEditedAt returns the old "edited_at" field's value of the ToDo entity.
// If the ToDo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ToDoMutation) OldEditedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEditedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEditedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEditedAt: %w", err)
	}
	return oldValue.EditedAt, nil
}

// ResetEditedAt resets all changes to the "edited_at" field.
func (m *ToDoMutation) ResetEditedAt() {
	m.edited_at = nil
}

// SetDeletedAt sets the "deleted_at" field.
func (m *ToDoMutation) SetDeletedAt(t time.Time) {
	m.deleted_at = &t
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *ToDoMutation) DeletedAt() (r time.Time, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the ToDo entity.
// If the ToDo object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ToDoMutation) OldDeletedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *ToDoMutation) ResetDeletedAt() {
	m.deleted_at = nil
}

// Where appends a list predicates to the ToDoMutation builder.
func (m *ToDoMutation) Where(ps ...predicate.ToDo) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ToDoMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (ToDo).
func (m *ToDoMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ToDoMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.todo_uuid != nil {
		fields = append(fields, todo.FieldTodoUUID)
	}
	if m.todo != nil {
		fields = append(fields, todo.FieldTodo)
	}
	if m._done != nil {
		fields = append(fields, todo.FieldDone)
	}
	if m.created_at != nil {
		fields = append(fields, todo.FieldCreatedAt)
	}
	if m.edited_at != nil {
		fields = append(fields, todo.FieldEditedAt)
	}
	if m.deleted_at != nil {
		fields = append(fields, todo.FieldDeletedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ToDoMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case todo.FieldTodoUUID:
		return m.TodoUUID()
	case todo.FieldTodo:
		return m.Todo()
	case todo.FieldDone:
		return m.Done()
	case todo.FieldCreatedAt:
		return m.CreatedAt()
	case todo.FieldEditedAt:
		return m.EditedAt()
	case todo.FieldDeletedAt:
		return m.DeletedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ToDoMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case todo.FieldTodoUUID:
		return m.OldTodoUUID(ctx)
	case todo.FieldTodo:
		return m.OldTodo(ctx)
	case todo.FieldDone:
		return m.OldDone(ctx)
	case todo.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case todo.FieldEditedAt:
		return m.OldEditedAt(ctx)
	case todo.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	}
	return nil, fmt.Errorf("unknown ToDo field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ToDoMutation) SetField(name string, value ent.Value) error {
	switch name {
	case todo.FieldTodoUUID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTodoUUID(v)
		return nil
	case todo.FieldTodo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTodo(v)
		return nil
	case todo.FieldDone:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDone(v)
		return nil
	case todo.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case todo.FieldEditedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEditedAt(v)
		return nil
	case todo.FieldDeletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	}
	return fmt.Errorf("unknown ToDo field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ToDoMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ToDoMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ToDoMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ToDo numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ToDoMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ToDoMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ToDoMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ToDo nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ToDoMutation) ResetField(name string) error {
	switch name {
	case todo.FieldTodoUUID:
		m.ResetTodoUUID()
		return nil
	case todo.FieldTodo:
		m.ResetTodo()
		return nil
	case todo.FieldDone:
		m.ResetDone()
		return nil
	case todo.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case todo.FieldEditedAt:
		m.ResetEditedAt()
		return nil
	case todo.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	}
	return fmt.Errorf("unknown ToDo field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ToDoMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ToDoMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ToDoMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ToDoMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ToDoMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ToDoMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ToDoMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ToDo unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ToDoMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ToDo edge %s", name)
}
