// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dev-hyunsang/golang-crud-with-entgo/ent/schema"
	"github.com/dev-hyunsang/golang-crud-with-entgo/ent/todo"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.ToDo{}.Fields()
	_ = todoFields
	// todoDescTodoUUID is the schema descriptor for todo_uuid field.
	todoDescTodoUUID := todoFields[0].Descriptor()
	// todo.DefaultTodoUUID holds the default value on creation for the todo_uuid field.
	todo.DefaultTodoUUID = todoDescTodoUUID.Default.(func() uuid.UUID)
	// todoDescTodo is the schema descriptor for todo field.
	todoDescTodo := todoFields[1].Descriptor()
	// todo.DefaultTodo holds the default value on creation for the todo field.
	todo.DefaultTodo = todoDescTodo.Default.(string)
	// todoDescDone is the schema descriptor for done field.
	todoDescDone := todoFields[2].Descriptor()
	// todo.DefaultDone holds the default value on creation for the done field.
	todo.DefaultDone = todoDescDone.Default.(bool)
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[3].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(time.Time)
	// todoDescEditedAt is the schema descriptor for edited_at field.
	todoDescEditedAt := todoFields[4].Descriptor()
	// todo.DefaultEditedAt holds the default value on creation for the edited_at field.
	todo.DefaultEditedAt = todoDescEditedAt.Default.(time.Time)
	// todoDescDeletedAt is the schema descriptor for deleted_at field.
	todoDescDeletedAt := todoFields[5].Descriptor()
	// todo.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	todo.DefaultDeletedAt = todoDescDeletedAt.Default.(time.Time)
}
