// Code generated by ent, DO NOT EDIT.

package todo

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the todo type in the database.
	Label = "to_do"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTodoUUID holds the string denoting the todo_uuid field in the database.
	FieldTodoUUID = "todo_uuid"
	// FieldTodo holds the string denoting the todo field in the database.
	FieldTodo = "todo"
	// FieldDone holds the string denoting the done field in the database.
	FieldDone = "done"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldEditedAt holds the string denoting the edited_at field in the database.
	FieldEditedAt = "edited_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the todo in the database.
	Table = "to_dos"
)

// Columns holds all SQL columns for todo fields.
var Columns = []string{
	FieldID,
	FieldTodoUUID,
	FieldTodo,
	FieldDone,
	FieldCreatedAt,
	FieldEditedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTodoUUID holds the default value on creation for the "todo_uuid" field.
	DefaultTodoUUID func() uuid.UUID
	// DefaultTodo holds the default value on creation for the "todo" field.
	DefaultTodo string
	// DefaultDone holds the default value on creation for the "done" field.
	DefaultDone bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultEditedAt holds the default value on creation for the "edited_at" field.
	DefaultEditedAt time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt time.Time
)
